name: Use Secret API

on: [push]

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call external API
        run: curl -H "Authorization: Bearer ${{ secrets.MY_SECRET }}" https://example.com/api

